### ISSUE TITLE
match for pattern '#test#'

### ISSUE THREAD

**Issue by xybu** [zb3/zgitignore#2]
It seems that the program does not handle `\#test#` pattern (if the file name begins with a '#' char, then the beginning hashtag should be escaped). I understand that there are other ways to write the pattern, but will there be a fix to solve the inconsistency?

**Comment by zb3** [comment]
Thanks for reporting and sorry for late reply.

It looks like there's been a bug with the "\" character, and I think I've fixed this.
Let me know if that works for you :)
